/** Vietnamese UI strings for admin (no locale routing). */
export const a = {
  siteTitle: "Quản trị — Car Retail",
  brand: "Car Retail Admin",
  brandSub: "CMS đại lý",
  menuToggle: "Mở/đóng menu",
  logout: "Đăng xuất",

  save: "Lưu",
  saving: "Đang lưu…",
  saved: "Đã lưu.",
  delete: "Xóa",
  deleting: "Đang xóa…",
  confirmDelete: "Xóa mục này?",
  deleteFailed: "Xóa thất bại",
  saveFailed: "Lưu thất bại",
  networkError: "Lỗi mạng",
  none: "— Không chọn —",
  preview: "Xem trước",
  upload: "Tải lên",
  uploading: "Đang tải lên…",
  uploadFailed: "Tải lên thất bại",
  uploadSuccess: "Đã tải lên",
  chooseFile: "Chọn tệp",
  published: "Đã xuất bản",
  draft: "Bản nháp",
  edit: "Sửa",
  add: "Thêm",
  update: "Cập nhật",
  exportCsv: "Xuất CSV",
  missingEn: "thiếu EN",

  nav: {
    dashboard: "📊 Tổng quan",
    settings: "⚙️ Cài đặt site",
    navigation: "🔀 Menu điều hướng",
    units: "📏 Đơn vị thông số",
    templates: "📋 Mẫu thông số",
    models: "🚗 Danh mục xe",
    media: "🖼️ Thư viện media",
    homepage: "🏠 Trang chủ",
    news: "📰 Tin tức",
    pages: "📄 Trang & FAQ",
    showrooms: "🏪 Showroom",
    leads: "📥 Khách hàng tiềm năng",
  },

  login: {
    title: "Đăng nhập quản trị",
    subtitle: "Nhập thông tin để quản lý hệ thống đại lý",
    email: "Email",
    password: "Mật khẩu",
    submit: "Đăng nhập",
    verifying: "Đang xác thực…",
    failed: "Đăng nhập thất bại",
  },

  media: {
    title: "Thư viện media",
    folder: "Thư mục",
    file: "Tệp",
    altVi: "Mô tả ảnh (VI)",
    altEn: "Mô tả ảnh (EN)",
    uploadR2: "Tải lên R2",
  },

  folders: {
    SITE: "Site",
    HEROES: "Banner",
    VEHICLES: "Xe",
    NEWS: "Tin tức",
    POLICIES: "Chính sách",
  },
};
